Areas/Frontend/Controllers/ActivityController.cs
using BASE.Areas.Frontend.Models;
using BASE.Areas.Frontend.Models.Extend;
using BASE.Areas.Frontend.Service;
using BASE.Extensions;
using BASE.Models;
using BASE.Models.DB;
using BASE.Models.Enums;
using BASE.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Win32;
using NPOI.SS.Formula.Functions;
using NPOI.SS.Formula.PTG;
using NPOI.XWPF.UserModel;
using System.IO;
using System.Net.Mail;

namespace BASE.Areas.Frontend.Controllers
{
    public class ActivityController : BaseController
    {
        private readonly IConfiguration _conf;
        private readonly AllCommonService _allCommonService;
        private readonly FileService _fileService;
        private readonly ActivityService _activityService;
        private readonly QuizService _quizService;
        private readonly MailService _mailService;
        private readonly BASE.Areas.Backend.Service.ExportService _exportService;

        public ActivityController(IConfiguration configuration,
            AllCommonService allCommonService,
            ActivityService activtyService,
            FileService fileService,
            QuizService quizService,
            MailService mailService,
            BASE.Areas.Backend.Service.ExportService exportService)
        {
            _conf = configuration;
            _allCommonService = allCommonService;
            _activityService = activtyService;
            _fileService = fileService;
            _quizService = quizService;
            _mailService = mailService;
            _exportService = exportService;
        }

        public async Task<IActionResult> List(String id = "")
        {
            VM_Activity data = new VM_Activity();
            switch (id)
            {
                case "截止報名":
                case "講座":
                case "課程":
                case "活動": 
                    data.Search.Category = id;
                    ViewBag.Title = "活動訊息 - " + id;
                    break;
                default:
                    data.Search.Category = "課程";
                    ViewBag.Title = "活動訊息 - 課程";
                    break;
            }

            try
            {
                //取資料
                IQueryable<ActivityExtend>? dataList = _activityService.GetActivityList(ref _message, data.Search);

                //分頁
                if (dataList != null)
                    data.ActivityExtendList = await PagerInfoService.GetRange(dataList, data.Search.PagerInfo);

                foreach(var item in data.ActivityExtendList)
                    item.Sections = _allCommonService.Lookup<TbActivitySection>(ref _message, x => x.ActivityId == item.Header.Id).ToList();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home", new { area = "Frontend" });
            }

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> List(VM_Activity datapost)
        {
            try
            {
                ViewBag.Title = "活動訊息 - " + datapost.Search.Category;

                //取資料
                IQueryable<ActivityExtend>? dataList = _activityService.GetActivityList(ref _message, datapost.Search);

                //分頁
                if (dataList != null)
                    datapost.ActivityExtendList = await PagerInfoService.GetRange(dataList, datapost.Search.PagerInfo);

                foreach (var item in datapost.ActivityExtendList)
                    item.Sections = _allCommonService.Lookup<TbActivitySection>(ref _message, x => x.ActivityId == item.Header.Id).ToList();

            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home", new { area = "Frontend" });
            }


            return View(datapost);
        }

        public async Task<IActionResult> Detail(string id)
        {
            

            VM_Activity data = new VM_Activity();

            string decrypt_id = EncryptService.AES.RandomizedDecrypt(id);

            try
            {
                data.ActivityExtendItem = _activityService.GetActivityExtendItem(ref _message, decrypt_id);

                ViewBag.Title = "活動訊息 - " + data.ActivityExtendItem.Header.Title;
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home", new { area = "Frontend" });
            }

            return View(data);
        }

        public async Task<IActionResult> Register(string id)
        {
            HttpContext.Session.Set(Backend.Models.SessionStruct.VerifyCode.Activity, new ValidImageHelper().RandomCode(5));

            VM_ActivityReigster data = new VM_ActivityReigster();

            string decrypt_id = EncryptService.AES.RandomizedDecrypt(id);

            try
            {
                data.Header = _allCommonService.Lookup<TbActivity>(ref _message, x => x.Id == decrypt_id).FirstOrDefault();

                ViewBag.Title = "活動報名 - " + data.Header.Title;

                if (data.Header.RegEndDate <= DateTime.Now)
                    throw new Exception("報名日期已過，請選擇別項活動");

                data.Sections = _activityService.GetSections(ref _message, decrypt_id).ToList();
                data.id = id;
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home", new { area = "Frontend" });
            }

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(VM_ActivityReigster data)
        {
            string decrypt_id = EncryptService.AES.RandomizedDecrypt(data.id);//postback後仍然要解密
            string Feature = "活動報名", Action = "新增";
            bool isSuccess = false; // 最終動作成功與否
            bool unCaughtError = false;  // 例外錯誤發生，特別記錄至 TbLog

            DateTime dtnow = DateTime.Now;
            TbActivityRegister? main = new TbActivityRegister();
            List<TbActivityRegisterSection>? RegSections = new List<TbActivityRegisterSection>();

            String code = HttpContext.Session.Get<String>(Backend.Models.SessionStruct.VerifyCode.Activity);
           
            data.Sections = _activityService.GetSections(ref _message, decrypt_id).ToList();

            if (code == data.VerifyCode)
            {
                try
                {
                    if (data.Main == null || data.RegisterSection == null || data.RegisterSection.Count() <= 0)
                    {
                        TempData["TempMsg"] = "資料回傳有誤，請重新操作！";
                    }

                    main.CompanyName = data.Main.CompanyName;
                    main.CompanyLocation = data.Main.CompanyLocation;
                    main.CompanyType = data.Main.CompanyType;
                    main.Name = data.Main.Name;
                    main.JobTitle = data.Main.JobTitle;
                    main.Phone = data.Main.Phone;
                    main.CellPhone = data.Main.CellPhone;
                    main.Email = data.Main.Email;
                    main.CompanyEmpAmount = data.Main.CompanyEmpAmount;
                    main.InfoFrom = String.Join(",", data.ckbsInfoFrom);
                    main.ActivityId = decrypt_id; //給解密後的ID
                    main.CreateDate = DateTime.Now;

                    foreach (var item in data.RegisterSection)
                    {
                        TbActivityRegisterSection m = new TbActivityRegisterSection();
                        m.ActivityId = decrypt_id;  //給解密後的ID
                        m.RegisterSectionId = item.RegisterSectionId;
                        m.RegisterSectionType = item.RegisterSectionType;
                        m.IsVegin = item.IsVegin;

                        RegSections.Add(m);
                    }

                    using (var transaction = _activityService.GetTransaction())
                    {
                        try
                        {
                            //新增
                            await _activityService.Insert(main, transaction);
                            //target_id = main.Id; //新增後的主鍵存起來

                            //新增場次
                            foreach (var reg in RegSections)
                            {
                                reg.RegisterId = main.Id;
                                await _activityService.Insert(reg, transaction);
                            }

                            transaction.Commit();
                            isSuccess = true;
                        }
                        catch (Exception ex)
                        {
                            _message += ex.ToString();
                            TempData["TempMsgDetail"] = "發生技術性錯誤，請聯絡技術人員或稍後再試一次";
                            unCaughtError = true;
                        }
                    }


                }
                catch (Exception ex)
                {
                    TempData["TempMsg"] = "伺服器連線異常，請檢查您的網路狀態後再試一次！";

                    _message += ex.ToString();
                    unCaughtError = true;
                }
            } 
            else
            {
                data.Header = _allCommonService.Lookup<TbActivity>(ref _message, x => x.Id == decrypt_id).FirstOrDefault();
                data.Sections = _activityService.GetSections(ref _message, decrypt_id).ToList();
                TempData["TempMsg"] = "驗證碼錯誤";
            }

            if (isSuccess)
            {
                TempData["CostomTempEmail"] = main.Email;

                var activity = _activityService.GetActivityExtendItem(ref _message, decrypt_id);
                var activity_user = _allCommonService.Lookup<TbUserInfo>(ref _message, x => x.UserId == activity.Header.CreateUser).FirstOrDefault();

                //日期格式:○月○日  ○:○-○:○ (實體/線上 )、○月○日  ○:○-○:○ (實體/線上 )···
                var datetimeFormat = @"{0} {1}-{2}";
                var dateFormat = @"{0}";

Areas/Frontend/Views/Activity/Checkin.cshtml
@using BASE.Service
@model BASE.Areas.Frontend.Models.VM_Checkin

@section Scripts {
}

@section Css {
}

@await Html.PartialAsync("_BannerPartial", new BASE.Areas.Frontend.Models.Extend.BannerPartial(){ Main = "活動訊息", Detail = "簽到" })

<div class="section pb-md-4 py-lg-5">
    <div class="container" id="content">
        <a accesskey="C" href="#" title="中央內容區塊" class="sr-only sr-only-focusable">:::</a>
        <div class="row justify-content-center">
            <div class="col-lg-10 col-12">
                <div class="registrationBox bg-white p-4">
                    <div class="row">
                        <div class="col-12 text-center border-bottom rb-title">
                            <h2 class="fc-green fw-bold"><span>活動簽到</span></h2>
                            <small>請輸入您報名的Email及姓名以進行簽到</small>
                        </div>
                    </div>
                    <form action="" method="post" class="row g-3 mt-2 align-items-center" enctype="multipart/form-data" data-parsley-validate="">
                        @Html.AntiForgeryToken()

                        <div class="col-md-12">
                            <p>您本次簽到的活動為: @Model.Activity.Title</p>
                            <p>報名場次為: @Model.Section.Day.ToString("yyyy / MM / dd") @Model.Section.StartTime.ToString(@"hh\:mm") ~ @Model.Section.EndTime.ToString(@"hh\:mm")</p>
                        </div>

                        <div class="col-md-4 col-12 form-group">
                            <label for="inputD" class="form-label">報名姓名<span class="fc-red ms-1">*</span></label>
                            @Html.TextBoxFor(x => x.Name, new { @class="form-control", placeholder="請輸入姓名", required="required"})
                        </div>
                        <div class="col-md-8 col-12">
                            <label for="inputEmail4" class="form-label">報名電子郵件<span class="fc-red ms-1">*</span></label>
                            @Html.TextBoxFor(x => x.Email, new { @class="form-control", placeholder="請輸入電子郵件", type="email", required="required"})
                        </div>
                        <div class="col-12">
                            <button class="btn btn-success w-100" type="submit">簽到</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Frontend/Views/Activity/Detail.cshtml
@using BASE.Service
@using Microsoft.AspNetCore.Html;
@model BASE.Areas.Frontend.Models.VM_Activity

@await Html.PartialAsync("_BannerPartial", new BASE.Areas.Frontend.Models.Extend.BannerPartial(){ Main = "活動訊息", Detail = Model.ActivityExtendItem.Header.Title })

@section Scripts
{
    @if (TempData["CostomTempEmail"] != null)
    {
        <script>
            $(document).ready(function () {
                var myModal = new bootstrap.Modal(document.getElementById('regisDoneModal'));
                myModal.show();
            });
        </script>
    }
}

<!-- ================================================== -->
<!-- 活動訊息 內頁-->
<!-- ================================================== -->
<div class="section pb-md-4 py-lg-5">
    <div class="container" id="content">
        <a accesskey="C" href="#" title="中央內容區塊" class="sr-only sr-only-focusable">:::</a>
        <div class="row">
            <!-- 左邊內容區塊 -->
            <div class="col-lg-9 col-12">
                <div class="activityPage mt-3 p-md-0 p-3">
                    <h2>@Model.ActivityExtendItem.Header.Title</h2>
                    <h3>@Model.ActivityExtendItem.Header.Subject</h3>

                    <img src="@Model.ActivityExtendItem.FileInfo.FilePath" class="img-fluid" alt="活動圖片: @Model.ActivityExtendItem.Header.Title">

                    <h4><i class="fa-regular fa-paper-plane me-3 fc-green" aria-hidden="true"></i>活動簡介</h4>
                    <p>
                        @{
                            String content = System.Text.RegularExpressions.Regex.Replace(Model.ActivityExtendItem.Header.Description, "<.*?>", String.Empty);
                                   content = content.Replace(Environment.NewLine, "<br />");
                        }
                        @(new HtmlString(content))
                    </p>
                </div>
            </div>

            <!-- 右邊報名區塊 -->
            <div class="col-lg-3 col-12">
                <div class="activityInfo bg-white p-4">
                    <div class="info-title">
                        <i class="fa-solid fa-book-open me-2 fc-green" aria-hidden="true"></i>
                        相關活動資訊
                    </div>
                    <div class="info-text row">
                        <div class="text">活動主題：@Model.ActivityExtendItem.Header.Subject</div>
                        <div class="text">活動地點：@Model.ActivityExtendItem.Header.Place</div>
                        <div class="text">活動日期：</div>

                        @foreach(var day in Model.ActivityExtendItem.Sections.GroupBy(x => x.Day))
                        {
                            <div class="dateBox col-12 col-md-6 col-lg-12">
                                <div class="act-time">
                                    <div class="act-date">
                                        <i class="fa-regular fa-calendar-days me-2 fc-ored" aria-hidden="true"></i>
                                        @day.Key.ToString("yyyy / MM / dd")
                                    </div>
                                    @foreach(var time in day) 
                                    {
                                        <div class="mt-2">
                                            <span class="bg-gray py-1 px-2 fs--1 rounded-pill">時段</span>
                                            @time.StartTime.ToString(@"hh\:mm")
                                            -
                                            @time.EndTime.ToString(@"hh\:mm")
                                        </div>
                                    }
                                </div>
                            </div>
                        }
                    </div>
                    <hr>
                    <div class="info-title">
                        <i class="fa-solid fa-user ms-1 me-2 fc-green" aria-hidden="true"></i>
                        報名名額
                    </div>
                    <div class="info-text">
                        <div><span class="fc-orange fw-bold fs-2">@Model.ActivityExtendItem.Header.Quota</span>人</div>
                    </div>
                    <hr>
                    <div class="info-title">
                        <i class="fa-solid fa-user-group me-2 fc-green" aria-hidden="true"></i>
                        報名對象
                    </div>
                    <div class="info-text">
                        <div>@Model.ActivityExtendItem.Header.RegisterFor</div>
                    </div>
                    <hr>
                    <div class="info-title">
                        <i class="fa-solid fa-circle-info ms-1 me-2 fc-green" aria-hidden="true"></i>
                        講師資訊
                    </div>
                    <div class="info-text">
                        <div>@Model.ActivityExtendItem.Header.LecturerInfo</div>
                    </div>

                    <div class="d-grid gap-2 mt-5">

                        @if(Model.ActivityExtendItem.Header.RegEndDate > DateTime.Now && Model.ActivityExtendItem.Header.IsPublish == true){
                        <a class="btn btn-primary" href="@Url.Action("Register", new { id = EncryptService.AES.RandomizedEncrypt(Model.ActivityExtendItem.Header.Id) })">
                            <i class="fa-solid fa-paper-plane me-2" aria-hidden="true"></i>馬上報名</a>
                        }

                        <a class="btn btn-outline-primary" href="@Url.Action("List", new { id= Model.ActivityExtendItem.Header.Category})">
                            <i class="fa-solid fa-chevron-left me-2" aria-hidden="true"></i>返回列表頁</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- 報名完成Modal -->
<div class="modal fade" id="regisDoneModal" tabindex="-1" aria-labelledby="regisDoneModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header border-0" id="regisDoneModalLabel">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                <img src="~/areas/frontend/img/subs-done.png" class="img-fluid mt-n1" alt="" />
                <div class="fs-2 fw-bold mb-4">報 名 完 成</div>
                <img src="~/areas/frontend/img/regis-done.png" class="img-fluid" alt="" />
                <p class="mt-4">恭喜您報名完成，<br>相關訊息會再寄到<span class="fc-blue">@TempData["CostomTempEmail"] </span>信箱。</p>
                <button type="button" class="btn btn-success mb-2 w-100" data-bs-dismiss="modal">確定</button>
            </div>
        </div>
    </div>
</div>

Areas/Frontend/Views/Activity/Quiz.cshtml
@using Microsoft.AspNetCore.Html;
@model BASE.Areas.Frontend.Models.VM_Quiz

@section Scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#frm').on('submit', function () {

                var isValid = true;
                $('.checkboxs.required').each(function(i, ele){
                    var container = $(ele);
                    var quiz = container.siblings('.form-label').clone()    //clone the element
                        .children() //select all the children
                        .remove()   //remove all the children
                        .end()  //again go back to selected element
                        .text();

                    if(container.find('input[type=checkbox]:checked').length <= 0){
                        alert('請選擇' + quiz.trim());
                        isValid = false;
                    }
                });

                console.log(isValid);
                if(isValid)
                {
                    //取得所有答題結果
                    var models = [];

                    var RegisterID = $('#hidRegisterID').val();
                    var QuizID = $('#hidQuizID').val();

                    $('.aQuiz').each(function(i, ele){
                        var type = $(ele).data('quzi-type');

                        var QuizOptionID = $(ele).find('.hidQuizOptionID').val();
                        var QuizDescription = $(ele).find('.hidQuizDescription').val();
                        var ResponseText = '';

                        switch(type){
                            case 2:
                                ResponseText= $(ele).find('input[type=text]').val();
                                console.log(ResponseText);
                                break;
                            case 3:
                                ResponseText = $(ele).find('input[type=radio]:checked').val();
                                console.log(ResponseText);
                                break;
                            case 4:
                                var checks = []; 
                                $(ele).find('input[type=checkbox]:checked').each(function(a, b){ 
                                    checks.push($(b).prop('value'));
                                });
                                ResponseText = checks.join('|');
                                console.log(ResponseText);
                                break;
                        }

                        models.push({
                            RegisterID: RegisterID,
                            QuizID: QuizID,
                            QuizOptionID: QuizOptionID,
                            ResponseText: ResponseText,
                            QuizDescription : QuizDescription
                        });

                    });

                    console.log(models);

                    var token = $('#frm').find('input:hidden[name="__X-XSRFVerificationToken"]').val();

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("ajaxQuiz", "Activity")',
                        data: { 
                            data : models,
                            QuizID: QuizID,
                            RegisterID: RegisterID
                        },
                        beforeSend: function (xhr) {
                            xhr.setRequestHeader("X-XSRF-TOKEN", token);
                        },
                        success: function (response) {
                            Swal.fire({
                                icon: response.isSuccess ? 'success' : 'error',
                                text: response.message,
                            }).then((result) => {
                                if (response.isSuccess)
                                    location.href='@Url.Action("Index", "Home")';
                            });
                        }
                    });

                }

                return false;
            });
        });
    </script>
}

@section Css{
    <style>
        .red { color: red; }
    </style>
}


@await Html.PartialAsync("_BannerPartial", new BASE.Areas.Frontend.Models.Extend.BannerPartial(){ Main = "活動訊息", Detail = "問卷填寫" })

<div class="section pb-md-4 py-lg-5">
    <div class="container" id="content">
        <a accesskey="C" href="#" title="中央內容區塊" class="sr-only sr-only-focusable">:::</a>
        <div class="row justify-content-center">
            <div class="col-lg-10 col-12">
                <div class="registrationBox bg-white p-4">
                    <div class="row">
                        <div class="col-12 text-center border-bottom rb-title">
                            <h2 class="fc-green fw-bold"><span>@Model.ExtendItem.Header.Name</span></h2>
@*                            <small>@(new HtmlString(Model.ExtendItem.Header.Description))</small>
*@                        </div>
                    </div>
                    <form action="" id="frm" method="post" class="row g-3 mt-2 align-items-center" enctype="multipart/form-data" data-parsley-validate="">
                        @Html.AntiForgeryToken()
                            
                        @*<div class="row">
                            <div class="col-12">
                                <h3>@Model.ExtendItem.Header.Name</h3>
                            </div>
                        </div>*@

                        <div class="row">
                            <div class="col-12">
                                @(new HtmlString(Model.ExtendItem.Header.Description))
                            </div>
                        </div>

                        <div class="row">

                            @foreach (var line in Model.ExtendItem.Lines)
                            {
                                switch (line.Type)
                                {
                                    case 1:
                                        <div class="col-12 mb-3">
                                            <h5>@line.QuizDescription</h5>
                                        </div>
                                        break;
                                    case 2:
                                        <div class="col-12 form-group mb-3 aQuiz" data-quzi-type="2">

                                            <span class="form-label">
                                                @if (line.IsRequired)
                                                {
                                                    <span class="red">*</span>
                                                }
                                                @line.QuizDescription
                                            </span>
                                            @if (!String.IsNullOrEmpty(line.FillDirection))
                                            {
                                                <span style="color:#666; font-size:small">@line.FillDirection</span>
                                            }
                                            <input type="text" class="form-control" @(line.IsRequired ? "required" : "") />
                                            <input type="hidden" class="hidQuizOptionID" value="@line.Id">
                                            <input type="hidden" class="hidQuizDescription" value="@line.QuizDescription">
                                        </div>
                                        break;
                                    case 3:
                                        <div class="col-12 form-group mb-3 aQuiz" data-quzi-type="3">
                                            <span class="form-label">
                                                @if (line.IsRequired)
                                                {
                                                    <span class="red">*</span>
                                                }
                                                @line.QuizDescription
                                            </span>
                                            @if (!String.IsNullOrEmpty(line.FillDirection))
                                            {
                                                <span style="color:#666; font-size:small">@line.FillDirection</span>
                                            }
                                            @{
                                                var options = line.Options.Split("|").ToList();
                                                var count = 1;
                                            }
                                                
                                            @foreach (var option in options)
                                            {
                                                <div class="form-check">
                                                    <input class="form-check-input" value="@option" type="radio" name="@line.Id" id="@(line.Id)_@count" @(line.IsRequired ? "required" : "")>
                                                    <label class="form-check-label" for="@(line.Id)_@count">@option</label>
                                                </div>
                                                count++;
                                            }
                                            <input type="hidden" class="hidQuizOptionID" value="@line.Id">
                                            <input type="hidden" class="hidQuizDescription" value="@line.QuizDescription">
                                        </div>
                                        break;
                                    case 4:
                                        <div class="col-12 form-group mb-3 aQuiz" data-quzi-type="4">
                                            <span class="form-label">
                                                @if (line.IsRequired)
                                                {
                                                    <span class="red">*</span>
                                                }
                                                @line.QuizDescription
                                            </span>
                                            @if (!String.IsNullOrEmpty(line.FillDirection))
                                            {
                                                <span style="color:#666; font-size:small">@line.FillDirection</span>
                                            }
                                            @{
                                                var ckbs = line.Options.Split("|").ToList();
                                                var count2 = 1;
                                            }

                                            <div class="checkboxs @(line.IsRequired ? "required" : "")">
                                            @foreach (var ckb in ckbs)
                                            {
                                                <div class="form-check">
                                                    <input class="form-check-input" value="@ckb" type="checkbox" name="@line.Id" id="@(line.Id)_@count2">
                                                    <label class="form-check-label" for="@(line.Id)_@count2">@ckb</label>
                                                </div>
                                                count2++;
                                            }
                                            </div>
                                            <input type="hidden" class="hidQuizOptionID" value="@line.Id">
                                            <input type="hidden" class="hidQuizDescription" value="@line.QuizDescription">
                                        </div>
                                        break;
                                }
                            }

                        </div>

                        <div class="row mt-4">
                            <div class="form-group">
                                <button class="btn btn-success w-100" type="submit">送出</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@Html.Hidden("hidRegisterID", Model.RegisterID)
@Html.Hidden("hidQuizID", Model.QuizID)