Areas/Backend/Controllers/YouTubeVideoController.cs
using BASE.Areas.Backend.Models;
using BASE.Areas.Backend.Models.Extend;
using BASE.Areas.Backend.Service;
using BASE.Extensions;
using BASE.Service;
using BASE.Models.Enums;
using Microsoft.AspNetCore.Mvc;
using BASE.Filters;
using BASE.Models.DB;
using Microsoft.EntityFrameworkCore;
using BASE.Models;
using System.Data.Entity;
using NPOI.SS.Formula.Functions;

namespace BASE.Areas.Backend.Controllers
{
    public class YouTubeVideoController : BaseController
    {
        private readonly AllCommonService _allCommonService;
        private readonly CommonService _commonService;
        private readonly YouTubeVideoService _ytvService;

        public YouTubeVideoController(AllCommonService allCommonService,
            CommonService commonService,
            YouTubeVideoService ytvService)
        {
            _allCommonService = allCommonService;
            _commonService = commonService;
            _ytvService = ytvService;
        }

        /// <summary>
        /// YouTubeVideoList列表
        /// </summary>
        /// <param name="data"></param>
        /// <returns></returns>
        [BackendCheckLogin("Menu000023", "ENABLED")]
        public async Task<IActionResult> YouTubeVideoList(VM_YouTubeVideo data)
        {
            UserSessionModel? userinfo = HttpContext.Session.Get<UserSessionModel>(SessionStruct.Login.UserInfo);
            string Feature = "影音專區管理", Action = "檢視";

            try
            {
                //取資料
                IQueryable<YouTubeVideoExtend>? dataList = _ytvService.GetYouTubeVideoExtendList(ref _message);

                //分頁
                if (dataList != null)
                    data.YouTubeVideoExtendList = await PagerInfoService.GetRange(dataList.OrderByDescending(x => x.YouTubeVideo.DisplayDate), data.Search.PagerInfo);

                //操作紀錄
                await _commonService.OperateLog(userinfo.UserID, Feature, Action, null, data);
            }
            catch (Exception ex)
            {
                TempData["TempMsgType"] = MsgTypeEnum.error;
                TempData["TempMsg"] = "伺服器連線異常，請檢查您的網路狀態後再試一次！";

                string response = (TempData["TempMsg"] == null ? "" : TempData["TempMsg"].ToString()) + "\r\n" + (TempData["TempMsgDetail"] == null ? "" : TempData["TempMsgDetail"].ToString());

                await _commonService.OperateLog(userinfo.UserID, Feature, Action, null, data, ex.ToString(), response, false);
                await _allCommonService.Error_Record("Backend", Feature + "-" + Action, ex.ToString());

                return RedirectToAction("Index", "Home", new { area = "Backend" });
            }

            return View(data);
        }

        /// <summary>
        /// 新增YouTubeVideo
        /// </summary>
        /// <returns></returns>
        [BackendCheckLogin("Menu000024", "ADD")]
        public async Task<IActionResult> YouTubeVideoAdd()
        {
            UserSessionModel? userinfo = HttpContext.Session.Get<UserSessionModel>(SessionStruct.Login.UserInfo);
            string Feature = "影音專區新增", Action = "新增";

            VM_YouTubeVideo data = new VM_YouTubeVideo();

            await _commonService.OperateLog(userinfo.UserID, Feature, Action);
            return View(data);
        }

        /// <summary>
        /// 新增YouTubeVideo存檔
        /// </summary>
        /// <param name="datapost"></param>
        /// <returns></returns>
        [BackendCheckLogin("Menu000024", "ADD")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> YouTubeVideoAdd(VM_YouTubeVideo datapost)
        {
            UserSessionModel? userinfo = HttpContext.Session.Get<UserSessionModel>(SessionStruct.Login.UserInfo);
            string Feature = "影音專區新增", Action = "新增";


            // 最終動作成功與否
            bool isSuccess = false;

            // 例外錯誤發生，特別記錄至 TbLog
            bool unCaughtError = false;

            DateTime dtnow = DateTime.Now;
            TbYouTubeVideo? item = new TbYouTubeVideo();
            string? target_id = null;

            try
            {
                if (datapost.YouTubeVideoExtendItem != null)
                {
                    item.Title = datapost.YouTubeVideoExtendItem.YouTubeVideo.Title;
                    item.DisplayDate = datapost.YouTubeVideoExtendItem.YouTubeVideo.DisplayDate;
                    item.YouTubeId = datapost.YouTubeVideoExtendItem.YouTubeVideo.YouTubeId;
                    item.IsDelete = false;
                    if (datapost.Search.sPublish == "上架")
                    { item.IsPublish = true; }
                    else
                    { item.IsPublish = false; }
                    item.CreateUser = userinfo.UserID;
                    item.CreateDate = dtnow;


                    using (var transaction = _ytvService.GetTransaction())
                    {
                        try
                        {
                            //新增
                            await _ytvService.Insert(item, transaction);

                            transaction.Commit();
                            isSuccess = true;
                            target_id = item.Id.ToString();
                        }
                        catch (Exception ex)
                        {
                            _message += ex.ToString();
                            TempData["TempMsgDetail"] = "發生技術性錯誤，請聯絡技術人員或稍後再試一次";
                            unCaughtError = true;
                        }
                    }
                }
                else
                {
                    TempData["TempMsg"] = "資料回傳有誤，請重新操作！";
                }
            }
            catch (Exception ex)
            {
                TempData["TempMsg"] = "伺服器連線異常，請檢查您的網路狀態後再試一次！";

                _message += ex.ToString();
                unCaughtError = true;
            }


            if (isSuccess)
            {
                TempData["TempMsgType"] = MsgTypeEnum.success;
                TempData["TempMsg"] = "儲存成功";
            }
            else
            {
                TempData["TempMsgType"] = MsgTypeEnum.error;
                TempData["TempMsg"] = TempData["TempMsg"] ?? "儲存失敗";

                if (unCaughtError)
                {
                    await _allCommonService.Error_Record("Backend", Feature + "-" + Action, _message);
                }
            }

            //操作紀錄
            string response = (TempData["TempMsg"] == null ? "" : TempData["TempMsg"].ToString()) + "\r\n" + (TempData["TempMsgDetail"] == null ? "" : TempData["TempMsgDetail"].ToString());
            await _commonService.OperateLog(userinfo.UserID, Feature, Action, target_id, datapost, _message, response, isSuccess);

            if (isSuccess)
            {
                return RedirectToAction("YouTubeVideoList");
            }
            else
            {
                if (item == null)
                {
                    return RedirectToAction("YouTubeVideoList");
                }
                else
                {
                    /* 失敗回原頁 */
                    return View(datapost);
                }
            }
        }

        /// <summary>
        /// 編輯YouTubeVideo
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [BackendCheckLogin("Menu000025", "MODIFY")]
        public async Task<IActionResult> YouTubeVideoEdit(int id)
        {
            UserSessionModel? userinfo = HttpContext.Session.Get<UserSessionModel>(SessionStruct.Login.UserInfo);
            string Feature = "影音專區編輯", Action = "檢視";

            VM_YouTubeVideo data = new VM_YouTubeVideo();

            // 最終動作成功與否
            bool isSuccess = false;

            // 例外錯誤發生，特別記錄至 TbLog
            bool unCaughtError = false;

            string decrypt_id = id.ToString();

            try
            {

                if (string.IsNullOrEmpty(decrypt_id))
                {
                    TempData["TempMsgDetail"] = "金鑰逾時！請重新再操作一次！";
                }
                else
                {
                    IQueryable<YouTubeVideoExtend>? dataList = _ytvService.GetYouTubeVideoxtendItem(ref _message, id);
                    if (dataList != null)
                        data.YouTubeVideoExtendItem = dataList.FirstOrDefault();

                    if (data.YouTubeVideoExtendItem == null)
                    {
                        TempData["TempMsgDetail"] = "查無指定項目！";
                    }
                    else
                    {
                        isSuccess = true;
                    }
                }

            }
            catch (Exception ex)
            {
                TempData["TempMsg"] = "伺服器連線異常，請檢查您的網路狀態後再試一次！";

                _message += ex.ToString();
                unCaughtError = true;
            }

            if (isSuccess)
            {
                await _commonService.OperateLog(userinfo.UserID, Feature, Action, decrypt_id, id.ToString());
                return View(data);
            }
            else
            {
                TempData["TempMsgType"] = MsgTypeEnum.error;
                TempData["TempMsg"] = TempData["TempMsg"] ?? "操作失敗";

                //操作紀錄
                string response = (TempData["TempMsg"] == null ? "" : TempData["TempMsg"].ToString()) + "\r\n" + (TempData["TempMsgDetail"] == null ? "" : TempData["TempMsgDetail"].ToString());
                await _commonService.OperateLog(userinfo.UserID, Feature, Action, decrypt_id, id.ToString(), _message, response, isSuccess);

                if (unCaughtError)
                {
                    await _allCommonService.Error_Record("Backend", Feature + "-" + Action, _message);
                }

                return RedirectToAction("YouTubeVideoList");
            }
        }

        /// <summary>
        /// 編輯YouTubeVideo_存檔
        /// </summary>
        /// <param name="id"></param>
        /// <param name="datapost"></param>
        /// <returns></returns>

Areas/Backend/Views/YouTubeVideo/YouTubeVideoAdd.cshtml
@model BASE.Areas.Backend.Models.VM_YouTubeVideo
@{
}

@section CustomScripts
    {
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    <script type="text/javascript">

        //報名區間_訖
        $('#YouTubeVideoExtendItem_YouTubeVideo_DisplayDate').daterangepicker({
            singleDatePicker: true,
            locale: {
                format: 'YYYY-MM-DD'
            }
        });

    </script>
    }
    <div class="card">
        <div class="card-body">
        @using (Html.BeginForm(FormMethod.Post, new { id = "frm", @autocomplete = "off", @enctype = "multipart/form-data", @data_parsley_validate = "" }))
        {
            @Html.AntiForgeryToken()
            <div class="row">
                <div class="col-12 form-group mb-3">
                    @Html.LabelFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.IsPublish, "狀態", new { @class = "form-label" })
                    @Html.DropDownListFor(x=>x.Search.sPublish,Model.ddlPublish,new{@class="form-control",id="ddlPublish"})
                </div>

                <div class="col-12 form-group mb-3">
                    <span class="red">*</span>
                    @Html.LabelFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.Title, "標題：", new { @class = "form-label" })
                    @Html.TextBoxFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.Title, new { @class="form-control", placeholder = "請輸入標題", data_parsley_required = "" })
                </div>

                <div class="col-12 form-group mb-3">
                    <span class="red">*</span>
                    @Html.LabelFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.DisplayDate, "日期", new { @class = "form-label" })
                    @Html.TextBoxFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.DisplayDate, new { @class="form-control daterange_selector", placeholder = "年/月/日", data_parsley_required = ""})
                </div>

                <div class="col-12 form-group mb-3">
                    <span class="red">*</span>
                    @Html.LabelFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.YouTubeId, "Youtube連結：", new { @class = "form-label" })
                    @Html.TextBoxFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.YouTubeId, new { @class="form-control", placeholder = "請輸入影片ID", data_parsley_required = "" })
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">儲存</button>
                    <a class="btn btn-light" href="@(Url.Action("YouTubeVideoList", "YouTubeVideo"))">取消</a>
                </div>
            </div>
        }
    </div>
</div>

Areas/Backend/Views/YouTubeVideo/YouTubeVideoEdit.cshtml
@model BASE.Areas.Backend.Models.VM_YouTubeVideo
@{
}

@section CustomScripts
    {
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    <script type="text/javascript">

        //報名區間_訖
        $('#YouTubeVideoExtendItem_YouTubeVideo_DisplayDate').daterangepicker({
            singleDatePicker: true,
            locale: {
                format: 'YYYY-MM-DD'
            }
        });

    </script>
    }
    <div class="card">
        <div class="card-body">
        @using (Html.BeginForm(FormMethod.Post, new { id = "frm", @autocomplete = "off", @enctype = "multipart/form-data", @data_parsley_validate = "" }))
        {
            @Html.AntiForgeryToken()
            <div class="row">
                <div class="col-12 form-group mb-3">
                    @Html.LabelFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.IsPublish, "狀態", new { @class = "form-label" })
                    @Html.DropDownListFor(x=>x.Search.sPublish,Model.ddlPublish,new{@class="form-control",id="ddlPublish"})
                </div>

                <div class="col-12 form-group mb-3">
                    <span class="red">*</span>
                    @Html.LabelFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.Title, "標題：", new { @class = "form-label" })
                    @Html.TextBoxFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.Title, new { @class="form-control", placeholder = "請輸入標題", data_parsley_required = "" })
                </div>

                <div class="col-12 form-group mb-3">
                    <span class="red">*</span>
                    @Html.LabelFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.DisplayDate, "日期", new { @class = "form-label" })
                    @Html.TextBoxFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.DisplayDate,"{0:yyyy-MM-dd}", new { @class="form-control daterange_selector", placeholder = "年/月/日", data_parsley_required = ""})
                </div>

                <div class="col-12 form-group mb-3">
                    <span class="red">*</span>
                    @Html.LabelFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.YouTubeId, "Youtube連結：", new { @class = "form-label" })
                    @Html.TextBoxFor(x => x.YouTubeVideoExtendItem.YouTubeVideo.YouTubeId, new { @class="form-control", placeholder = "請輸入影片ID", data_parsley_required = "" })
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">儲存</button>
                    <a class="btn btn-light" href="@(Url.Action("YouTubeVideoList", "YouTubeVideo"))">取消</a>
                </div>
            </div>
        }
    </div>
</div>

Areas/Backend/Views/YouTubeVideo/YouTubeVideoList.cshtml
@using BASE.Extensions
@model BASE.Areas.Backend.Models.VM_YouTubeVideo
@section CustomScripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
        });

        function Delete(id) {
            Swal.fire({
                title: '提示訊息',
                text: '你是否要刪除影音專區？',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: '刪除',
                cancelButtonText: '取消',
            }).then((r) => {
                if (r.isConfirmed) {

                    $.blockUI();

                    //確定刪除
                    $.ajax({
                        type: "Post",
                        url: "@(Url.Action("YouTubeVideoDelete", "YouTubeVideo"))",
                        dataType: "json",
                        beforeSend: function (request) {
                            request.setRequestHeader("X-XSRF-TOKEN", $('input[name="__X-XSRFVerificationToken"]').val());
                        },
                        data: { id: id },
                        success: function (result) {
                            $.unblockUI();
                            inform({
                                plugin: result.alert_plugin,
                                type: result.alert_type,
                                title: result.message,
                                content: result.messageDetail,
                                redirect_url: ""
                            });
                        }
                    });
                } else {
                    //任何方式的取消
                    Swal.fire('刪除', '取消成功', 'success');
                }
            });
        }

        function PublishChange(id) {
            Swal.fire({
                title: '提示訊息',
                text: '是否變更上下架狀態？',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: '是',
                cancelButtonText: '否',
            }).then((r) => {
                if (r.isConfirmed) {

                    $.blockUI();

                    //確定變更狀態
                    $.ajax({
                        type: "Post",
                        url: "@(Url.Action("YouTubeVideoPublishChange", "YouTubeVideo"))",
                        dataType: "json",
                        beforeSend: function (request) {
                            request.setRequestHeader("X-XSRF-TOKEN", $('input[name="__X-XSRFVerificationToken"]').val());
                        },
                        data: { id: id },
                        success: function (result) {
                            $.unblockUI();
                            inform({
                                plugin: result.alert_plugin,
                                type: result.alert_type,
                                title: result.message,
                                content: result.messageDetail,
                                redirect_url: ""
                            });
                        }
                    });
                } else {
                    //任何方式的取消
                    Swal.fire('變更狀態', '取消成功', 'success');
                }
            });
        }

    </script>
}

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                @using (Html.BeginForm(FormMethod.Get, new { id = "frm", @autocomplete = "off" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(x => x.Search.PagerInfo.m_iPageIndex, new { @class="hiddenCurrentPage" })
                    @Html.HiddenFor(x => x.Search.PagerInfo.m_iPageCount, new { @class="hiddenPageCount" })
                    @Html.HiddenFor(x => x.Search.PagerInfo.m_Search, new { @class="pager-Info-Search" })

                    <div class="row g-3 align-items-end mb-3">
                        <div class="col-12 col-md-auto ms-auto">
                            <a class="btn btn-primary" href="@(Url.Action("YouTubeVideoAdd", "YouTubeVideo"))">新增</a>
                        </div>
                    </div>
                }

                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead class="table-light">
                            <tr>
                                <th>項次</th>
                                <th>標題</th>
                                <th>日期</th>
                                <th>影音專區ID</th>
                                <th>狀態</th>
                                <th>管理</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.YouTubeVideoExtendList != null && Model.YouTubeVideoExtendList.Count > 0)
                            {
                                foreach (var item in Model.YouTubeVideoExtendList)
                                {
                                    <tr>
                                        <td>@(Model.YouTubeVideoExtendList.IndexOf(item) + 1)</td>
                                        <td style="max-width:30vw;">@item.YouTubeVideo.Title</td>
                                        <td>@item.YouTubeVideo.DisplayDate.ToString("yyyy-MM-dd")</td>
                                        <td>@item.YouTubeVideo.YouTubeId</td>
                                        @{
                                           string Status = string.Empty;
                                            string ButtonInfo = string.Empty;
                                            if (item.YouTubeVideo.IsPublish)
                                            {
                                                Status = "上架中";
                                                ButtonInfo = "下架";
                                            }
                                            else
                                            {
                                                Status = "已下架";
                                                ButtonInfo = "上架";
                                            }
                                        }
                                        <td style="max-width:55vw;">@Status</td>
                                        <td>
                                            <a class="btn btn-primary" href="@(Url.Action("YouTubeVideoEdit", "YouTubeVideo", new { id =item.YouTubeVideo.Id }))">編輯</a>
                                            @if (ButtonInfo == "上架")
                                            {
                                                <button type="button" class="btn btn-success" onclick="PublishChange('@(item.YouTubeVideo.Id)')">上架</button>
                                            }
                                            else
                                            {
                                                <button type="button" class="btn btn-outline-success" onclick="PublishChange('@(item.YouTubeVideo.Id)')">下架</button>
                                            }
                                            <button type="button" class="btn btn-danger" onclick="Delete('@(item.YouTubeVideo.Id)')">刪除</button>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr><td colspan="4">目前暫無資料</td></tr>
                            }
                        </tbody>
                    </table>
                </div>
                @if (Model != null && Model.YouTubeVideoExtendList != null && Model.YouTubeVideoExtendList.Count > 0)
                {
                    @await Html.PartialAsync("_Pagination", Model.Search.PagerInfo)
                }
            </div>
        </div>
    </div>
</div>